### PR TITLE
Fix #clean_cache! to delete cache dirs under uploader root

### LINKED ISSUE #2113: cache directory can't delete.
I want to delete temporary files for uploading on carrierwave.
I don't to set a parameter of "config.delete_tmp_file_after_storage". (This parameter is true as default.)
But My temporary files can't delete after uploading.
Do you know this problem?

**My environment**
```
Ubuntu 16.04LTS
ruby 2.4.0p0 (2016-12-24 revision 57164)
rails 5.0.1
carrierwave 1.0.0
fog 1.38.0
```

**config/initializers/carrierwave.rb**
```
CarrierWave.configure do |config|
  config.fog_credentials = {
    provider:              'AWS',
    region:                'xxxxxxxx'
  }.merge Settings.fog_credentials || {}

  # For testing, upload files to local `tmp` folder.
  if Rails.env.test? || Rails.env.cucumber?
    config.storage = :file
    config.enable_processing = false
    config.root = "#{Rails.root}/tmp"
  else
    config.storage = :fog
  end

  config.fog_directory = Settings.fog_directory
  config.fog_public    = true
  # use Japanese
  CarrierWave::SanitizedFile.sanitize_regexp = /[^[:word:]\.\-\+]/
end

```

**base_image_uploader.rb**
```
class BaseImageUploader < ImageUploader
  ......

  def move_to_store
    true
  end

  def move_to_cache
    true
  end

  def cache_dir
    "/tmp/uploads/images"
  end

  ......
end
```

**after uploading, temporary directory's status**
```
ubuntu@ip-xxxxxxxx:/tmp/uploads/images/1486091031-30865-0001-5400$ ls
code_1.jpg  code_big_1.jpg  code_normal_1.jpg  code_thumb_1.jpg
```

### PR DESCRIPTION
**Pull request by sawasaki-narumi**
CarrierWave::Storage::File#clean_cache! can't delete cache direcotries if the uploader's root has changed.
This PR fix it.

[Fixes #2113]

### CODE REVIEW

File: spec/storage/file_spec.rb [hunk 1]
```diff
@@ -72,19 +72,19 @@
     after { FileUtils.rm_rf(cache_dir) }
 
     it "clears all files older than now in the default cache directory" do
-      Timecop.freeze(today) { uploader_class.clean_cached_files!(0) }
+      Timecop.freeze(today) { storage.clean_cache!(0) }
```
Comment (mshibuya) [inline spec/storage/file_spec.rb:75]: Please don't change these calls for `#clean_cached_files!`. This should be considered as a public API which needs to be tested.

To allow it to be executed for a specific uploader class, you'll need this change.

https://github.com/carrierwaveuploader/carrierwave/blob/a67bfb696dcba14c7cdfa2c1b5481f04d3ef8dae/lib/carrierwave/uploader/cache.rb#L68

```diff
-          (cache_storage || storage).new(CarrierWave::Uploader::Base.new).clean_cache!(seconds)
+          (cache_storage || storage).new(new).clean_cache!(seconds)
```

File: spec/storage/file_spec.rb [hunk 2]
```diff
@@ -59,7 +59,7 @@
     let(:five_days_ago) { today.ago(5.days) }
     let(:three_days_ago) { today.ago(3.days) }
     let(:yesterday) { today.yesterday }
-    let(:cache_dir) { File.expand_path(uploader_class.cache_dir, CarrierWave.root) }
+    let(:cache_dir) { File.expand_path(uploader_class.cache_dir, uploader.root) }
```
Comment (mshibuya) [inline spec/storage/file_spec.rb:62]: Is this necessary?
