### PR TITLE
fix: ruby 2.7 kwarg warning in uploader process

### LINKED ISSUE #2635: Ruby 2.7 Kwarg warning for Uploader#process
I use MiniMagick for image processing and I have a constant `PROCESSING_OPTIONS = [553, 553, { combine_options: { quality: '100', unsharp: '0x1+1+0.065' } }]` in my uploader and a `process resize_to_fill: PROCESSING_OPTIONS`

this raises a [ruby kwarg warning](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) at https://github.com/carrierwaveuploader/carrierwave/blob/b104d0f0e0562ec7457973a8c6e730b90231c14f/lib/carrierwave/uploader/processing.rb#L94

### PR DESCRIPTION
**Pull request by nachiket87**
fix #2635

### CODE REVIEW

File: lib/carrierwave/uploader/processing.rb [hunk 1]
```diff
@@ -65,7 +65,11 @@ def process(*args)
           condition_type = new_processors.keys.select { |key| [:if, :unless].include?(key) }[0]
           condition = new_processors.delete(:if) || new_processors.delete(:unless)
           new_processors.each do |processor, processor_args|
-            self.processors += [[processor, processor_args, condition, condition_type]]
+            if processor_args.is_a? Array
+              processor_kwargs, processor_args = processor_args.partition { |processor_arg| processor_arg.is_a? Hash }
+              processor_kwargs = processor_kwargs.reduce(:merge)
```
Comment (mshibuya) [inline lib/carrierwave/uploader/processing.rb:70]: Isn't it simpler to perform this separation inside `#process!`, not here?

File: spec/uploader/processing_spec.rb [hunk 2]
```diff
@@ -52,10 +52,10 @@
 
     context "when there is an 'if' condition" do
       it "calls the processor if the condition method returns true" do
-        uploader_class.process :resize => [200, 300], :if => :true?
+        uploader_class.process :resize => [200, 300, combine_options: { quality: 70 }], :if => :true?
         uploader_class.process :fancy, :if => :true?
         expect(uploader).to receive(:true?).with("test.jpg").twice.and_return(true)
-        expect(uploader).to receive(:resize).with(200, 300)
+        expect(uploader).to receive(:resize).with(200, 300, combine_options: { quality: 70 })
```
Comment (mshibuya) [inline spec/uploader/processing_spec.rb:58]: Do not modify an unrelated spec, you should create a new one instead.

Comment (nachiket87) [reply spec/uploader/processing_spec.rb]: Sure! thanks for the review!

File: lib/carrierwave/uploader/processing.rb (hunk 1 above)
Comment (nachiket87) [reply lib/carrierwave/uploader/processing.rb]: Yes, you're right. Felt like it would be more readable in the process method but you're right, it's much easier in the `process!` method. Thanks for the review!

**Comment by mshibuya** [comment]
Thank you!

**Comment by nachiket87** [comment]
@mshibuya can this be back-ported to v2 ?

**Comment by mshibuya** [comment]
Please open a PR for that. I can merge and make a new release.
